### PR TITLE
gh-75 fixing babel cache issue

### LINKED ISSUE #75: .env file variables are cached
.env changes are not propagated to code.

If you update .env, new values will not be detected until you change the file that imports the variables.

### PR DESCRIPTION
**Pull request by goatandsheep**
## Link to issue ##

fixes #75

## Description of changes being made ##

* refactor to work with new babel version

### CODE REVIEW

**Comment by goatandsheep** [comment]
This will duplicate functionality so closes #290

File: index.js [hunk 1]
```diff
@@ -18,110 +18,170 @@ function parseDotenvFile(path, verbose = false) {
...
+    whitelist: null,
+    blacklist: null,
+    allowlist: null,
+    blocklist: null,
+    safe: false,
+    allowUndefined: true,
+    verbose: false,
+    ...options,
+  }
+  const babelMode = process.env[options.envName] || (process.env.BABEL_ENV && process.env.BABEL_ENV !== 'undefined' && process.env.BABEL_ENV !== 'development' && process.env.BABEL_ENV) || process.env.NODE_ENV || 'development'
```
Comment (nicolo-ribaudo) [inline index.js:36]: You might want to wrap this in `cache.using`, so that if the env changes without restarting Node.js the plugin is reinstantiated.

Comment (goatandsheep) [reply index.js:37]: thank you! I moved things around. I still don't know if it will reload properly in hot reload, but I don't think the environment mode can change without a js reload so I left that out. Hopefully it works in other tests when we release it in `@next`!

Comment (goatandsheep) [reply index.js:37]: I am the second maintainer to this project so I'm not even sure about how all the babel features work

File: index.js [hunk 2]
```diff
@@ -18,110 +18,148 @@ function parseDotenvFile(path, verbose = false) {
...
 
-    const babelMode = process.env[this.opts.envName] || (process.env.BABEL_ENV && process.env.BABEL_ENV !== 'undefined' && process.env.BABEL_ENV !== 'development' && process.env.BABEL_ENV) || process.env.NODE_ENV || 'development'
-    if (this.opts.verbose) {
-      console.log('dotenvMode', babelMode)
-    }
+  if (options.verbose) {
+    console.log('dotenvMode', babelMode)
+  }
+
+  api.cache.using(() => {
```
Comment (nicolo-ribaudo) [inline index.js:46]: The function passed to `api.cache.using` should return a value that, when it changes, causes the plugin to be re-instantiated. Since this one always returns `undefined`, the plugin will never be re-instantiated and it will always use the initial `.env` file.

I suggest doing something like this:
```js
function mtime(filePath) {
  try {
    return fs.statSync(filePath).mtimeMs
  } catch {
    return null
  }
}

api.cache.using(() => mtime(options.path))
api.cache.using(() => mtime(localFilePath))
api.cache.using(() => mtime(modeFilePath))
api.cache.using(() => mtime(modeLocalFilePath))

let env

if (options.safe) {
  const parsed = parseDotenvFile(options.path, options.verbose)
  const localParsed = parseDotenvFile(localFilePath, options.verbose)
  const modeParsed = parseDotenvFile(modeFilePath, options.verbose)
  const modeLocalParsed = parseDotenvFile(modeLocalFilePath, options.verbose)
  
  env = Object.assign(Object.assign(Object.assign(parsed, modeParsed), localParsed), modeLocalParsed)
} else {
  dotenv.config({
    path: modeLocalFilePath,
    silent: true,
  })
  dotenv.config({
    path: modeFilePath,
    silent: true,
  })
  dotenv.config({
    path: localFilePath,
    silent: true,
  })
  dotenv.config({
    path: options.path,
  })
      
  env = process.env
}

```

Comment (goatandsheep) [reply index.js:46]: so when it is re-initialized, `pre()` is rerun?

**Comment by goatandsheep** [comment]
Codecoverage issue

File: index.js (hunk 2 above)
Comment (goatandsheep) [reply index.js]: so I found that this did not work in tests unfortunately. do I also need to use `addExternalDependency`?
